/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.Admin;

import java.awt.CardLayout;
import java.awt.Color;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JPanel;
import static javax.swing.SwingUtilities.getWindowAncestor;

/**
 *
 * @author apoorva
 */
public class AdminDashBoardJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AdminDashBoardJPanel
     */
    private Statement statement;
    private Connection connection;

    public AdminDashBoardJPanel(Statement statement, Connection connection) throws SQLException {
        initComponents();
        this.statement = statement;
        this.connection = connection;
        ManageAppointmentPanel manageOrgs = new ManageAppointmentPanel(statement, userProcessContainer, connection);
        userProcessContainer.add("ManageOrgsJPanel", manageOrgs);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane4 = new javax.swing.JSplitPane();
        manageAdmin = new javax.swing.JPanel();
        managePatientBtn = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        manageAppointmentsBtn = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        exit = new javax.swing.JLabel();
        manageEquipment = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        chartsBtn = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        userProcessContainer = new javax.swing.JPanel();

        setPreferredSize(new java.awt.Dimension(1100, 800));

        jSplitPane4.setBackground(new java.awt.Color(55, 96, 128));
        jSplitPane4.setDividerSize(0);

        manageAdmin.setBackground(new java.awt.Color(93, 113, 128));

        managePatientBtn.setBackground(new java.awt.Color(23, 35, 51));
        managePatientBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                managePatientBtnMousePressed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Manage Patients");

        javax.swing.GroupLayout managePatientBtnLayout = new javax.swing.GroupLayout(managePatientBtn);
        managePatientBtn.setLayout(managePatientBtnLayout);
        managePatientBtnLayout.setHorizontalGroup(
            managePatientBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(managePatientBtnLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        managePatientBtnLayout.setVerticalGroup(
            managePatientBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(managePatientBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE)
                .addContainerGap())
        );

        manageAppointmentsBtn.setBackground(new java.awt.Color(23, 35, 51));
        manageAppointmentsBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                manageAppointmentsBtnMousePressed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Manage Appointments");

        javax.swing.GroupLayout manageAppointmentsBtnLayout = new javax.swing.GroupLayout(manageAppointmentsBtn);
        manageAppointmentsBtn.setLayout(manageAppointmentsBtnLayout);
        manageAppointmentsBtnLayout.setHorizontalGroup(
            manageAppointmentsBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(manageAppointmentsBtnLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                .addContainerGap())
        );
        manageAppointmentsBtnLayout.setVerticalGroup(
            manageAppointmentsBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(manageAppointmentsBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        exit.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        exit.setForeground(new java.awt.Color(255, 255, 255));
        exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/sign-out.png"))); // NOI18N
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                exitMousePressed(evt);
            }
        });

        manageEquipment.setBackground(new java.awt.Color(23, 35, 51));
        manageEquipment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                manageEquipmentMousePressed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Manage Equipments");

        javax.swing.GroupLayout manageEquipmentLayout = new javax.swing.GroupLayout(manageEquipment);
        manageEquipment.setLayout(manageEquipmentLayout);
        manageEquipmentLayout.setHorizontalGroup(
            manageEquipmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(manageEquipmentLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        manageEquipmentLayout.setVerticalGroup(
            manageEquipmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(manageEquipmentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        chartsBtn.setBackground(new java.awt.Color(23, 35, 51));
        chartsBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                chartsBtnMousePressed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Charts");

        javax.swing.GroupLayout chartsBtnLayout = new javax.swing.GroupLayout(chartsBtn);
        chartsBtn.setLayout(chartsBtnLayout);
        chartsBtnLayout.setHorizontalGroup(
            chartsBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(chartsBtnLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        chartsBtnLayout.setVerticalGroup(
            chartsBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(chartsBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout manageAdminLayout = new javax.swing.GroupLayout(manageAdmin);
        manageAdmin.setLayout(manageAdminLayout);
        manageAdminLayout.setHorizontalGroup(
            manageAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(managePatientBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(manageAppointmentsBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(exit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(manageEquipment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(chartsBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        manageAdminLayout.setVerticalGroup(
            manageAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(manageAdminLayout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addComponent(chartsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(manageAppointmentsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(managePatientBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(manageEquipment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(443, Short.MAX_VALUE))
        );

        jSplitPane4.setLeftComponent(manageAdmin);

        userProcessContainer.setLayout(new java.awt.CardLayout());
        jSplitPane4.setRightComponent(userProcessContainer);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 974, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane4)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void managePatientBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_managePatientBtnMousePressed
        // TODO add your handling code here:
        setColor(managePatientBtn);
        resetColor(new JPanel[]{manageAppointmentsBtn});
        CreatePatientPanel manageEmp = new CreatePatientPanel(statement, userProcessContainer);
        userProcessContainer.add("ManageEmpJPanel", manageEmp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);

    }//GEN-LAST:event_managePatientBtnMousePressed

    private void manageAppointmentsBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageAppointmentsBtnMousePressed
        // TODO add your handling code here:
        setColor(manageAppointmentsBtn);
        resetColor(new JPanel[]{managePatientBtn});
        ManageAppointmentPanel manageOrgs = null;
        try {
            manageOrgs = new ManageAppointmentPanel(statement, userProcessContainer, connection);
        } catch (SQLException ex) {
            Logger.getLogger(AdminDashBoardJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        userProcessContainer.add("ManageOrgsJPanel", manageOrgs);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageAppointmentsBtnMousePressed

    private void exitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMousePressed
        // TODO add your handling code here:
        JFrame frame = (JFrame) getWindowAncestor(this);
        frame.dispose();
    }//GEN-LAST:event_exitMousePressed

    private void manageEquipmentMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageEquipmentMousePressed
        // TODO add your handling code here:
        setColor(manageEquipment);
        resetColor(new JPanel[]{managePatientBtn,manageAppointmentsBtn});
        EquipmentsPanel manageEqp;
        try {
            manageEqp = new EquipmentsPanel(statement, userProcessContainer,connection);
            userProcessContainer.add("EquipmentsPanel", manageEqp);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
        } catch (SQLException ex) {
            Logger.getLogger(AdminDashBoardJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
      
    }//GEN-LAST:event_manageEquipmentMousePressed

    private void chartsBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chartsBtnMousePressed
        // TODO add your handling code here:
        Charts chartPanel;
        chartPanel = new Charts(statement, userProcessContainer,connection);
        userProcessContainer.add("Charts", chartPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_chartsBtnMousePressed

    private void setColor(JPanel pane) {
        pane.setBackground(new Color(41, 57, 80));
    }

    private void resetColor(JPanel[] pane) {
        for (int i = 0; i < pane.length; i++) {
            pane[i].setBackground(new Color(23, 35, 51));

        }

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel chartsBtn;
    private javax.swing.JLabel exit;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSplitPane jSplitPane4;
    private javax.swing.JPanel manageAdmin;
    private javax.swing.JPanel manageAppointmentsBtn;
    private javax.swing.JPanel manageEquipment;
    private javax.swing.JPanel managePatientBtn;
    private javax.swing.JPanel userProcessContainer;
    // End of variables declaration//GEN-END:variables
}
