/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.Admin;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author apoorva
 */
public class CreatePatientPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageEnterpriseJPanel
     */
    private Statement statement;
    private JPanel userProcessContainer;
    private long pId;

    public CreatePatientPanel(Statement statement, JPanel userProcessContainer) {
        initComponents();
        this.statement = statement;
        updateButton.setEnabled(false);
        ButtonGroup medications = new ButtonGroup();
        medications.add(medYes);
        medications.add(medNo);

        ButtonGroup medications3 = new ButtonGroup();
        medications3.add(anastheticNo);
        medications3.add(anastheticYes);


        ButtonGroup medications6 = new ButtonGroup();
        medications6.add(otherNo);
        medications6.add(otherYes);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        nameSeparator3 = new javax.swing.JSeparator();
        nameTextField = new javax.swing.JTextField();
        add2TextField = new javax.swing.JTextField();
        nameSeparator2 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        addressJTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        nameSeparator1 = new javax.swing.JSeparator();
        middleNameTextField = new javax.swing.JTextField();
        nameSeparator = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        zipTextField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        nameSeparator7 = new javax.swing.JSeparator();
        nameSeparator4 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        contactTextField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        genderComboBox = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        nameSeparator5 = new javax.swing.JSeparator();
        nameSeparator6 = new javax.swing.JSeparator();
        nameSeparator9 = new javax.swing.JSeparator();
        emailTextField = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        nameSeparator8 = new javax.swing.JSeparator();
        emergencyContactJTextField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lastNameTextField = new javax.swing.JTextField();
        nameSeparator11 = new javax.swing.JSeparator();
        jXDatePicker2 = new org.jdesktop.swingx.JXDatePicker();
        saveButton = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();
        startUpdateButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        medYes = new javax.swing.JRadioButton();
        medNo = new javax.swing.JRadioButton();
        anastheticYes = new javax.swing.JRadioButton();
        anastheticNo = new javax.swing.JRadioButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        otherYes = new javax.swing.JRadioButton();
        otherNo = new javax.swing.JRadioButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        addMedicalHistoryButton = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        policyNumber = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        providerTxt = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        maxCoverageTxt = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        beginDatePicker = new org.jdesktop.swingx.JXDatePicker();
        endDatePicker = new org.jdesktop.swingx.JXDatePicker();
        jPanel5 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        addInsuranceButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(55, 96, 128));
        setMaximumSize(new java.awt.Dimension(1000, 800));
        setPreferredSize(new java.awt.Dimension(1100, 600));

        jPanel1.setBackground(new java.awt.Color(55, 96, 128));
        jPanel1.setPreferredSize(new java.awt.Dimension(947, 700));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        jLabel6.setText("Address Line 1");

        nameSeparator3.setForeground(new java.awt.Color(0, 0, 0));

        nameTextField.setBackground(new java.awt.Color(55, 96, 128));
        nameTextField.setBorder(null);
        nameTextField.setCaretColor(new java.awt.Color(55, 96, 128));
        nameTextField.setDisabledTextColor(new java.awt.Color(55, 96, 128));
        nameTextField.setOpaque(false);
        nameTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nameTextFieldFocusGained(evt);
            }
        });
        nameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTextFieldActionPerformed(evt);
            }
        });

        add2TextField.setBackground(new java.awt.Color(55, 96, 128));
        add2TextField.setBorder(null);
        add2TextField.setCaretColor(new java.awt.Color(30, 59, 92));
        add2TextField.setDisabledTextColor(new java.awt.Color(55, 96, 128));
        add2TextField.setOpaque(false);
        add2TextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                add2TextFieldFocusGained(evt);
            }
        });
        add2TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add2TextFieldActionPerformed(evt);
            }
        });

        nameSeparator2.setForeground(new java.awt.Color(0, 0, 0));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        jLabel5.setText("Address Line 2");

        addressJTextField.setBackground(new java.awt.Color(55, 96, 128));
        addressJTextField.setBorder(null);
        addressJTextField.setCaretColor(new java.awt.Color(30, 59, 92));
        addressJTextField.setDisabledTextColor(new java.awt.Color(55, 96, 128));
        addressJTextField.setOpaque(false);
        addressJTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                addressJTextFieldFocusGained(evt);
            }
        });
        addressJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressJTextFieldActionPerformed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        jLabel3.setText("Middle Name");

        nameSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        middleNameTextField.setBackground(new java.awt.Color(55, 96, 128));
        middleNameTextField.setBorder(null);
        middleNameTextField.setCaretColor(new java.awt.Color(30, 59, 92));
        middleNameTextField.setDisabledTextColor(new java.awt.Color(55, 96, 128));
        middleNameTextField.setOpaque(false);
        middleNameTextField.setSelectedTextColor(new java.awt.Color(55, 96, 128));
        middleNameTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                middleNameTextFieldFocusGained(evt);
            }
        });
        middleNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                middleNameTextFieldActionPerformed(evt);
            }
        });

        nameSeparator.setForeground(new java.awt.Color(0, 0, 0));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        jLabel2.setText("First Name");

        zipTextField.setBackground(new java.awt.Color(55, 96, 128));
        zipTextField.setBorder(null);
        zipTextField.setCaretColor(new java.awt.Color(30, 59, 92));
        zipTextField.setDisabledTextColor(new java.awt.Color(55, 96, 128));
        zipTextField.setOpaque(false);
        zipTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                zipTextFieldFocusGained(evt);
            }
        });
        zipTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zipTextFieldActionPerformed(evt);
            }
        });

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        jLabel10.setText("Zip Code");

        nameSeparator7.setForeground(new java.awt.Color(0, 0, 0));

        nameSeparator4.setForeground(new java.awt.Color(0, 0, 0));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        jLabel7.setText("Contact");

        contactTextField.setBackground(new java.awt.Color(55, 96, 128));
        contactTextField.setBorder(null);
        contactTextField.setCaretColor(new java.awt.Color(30, 59, 92));
        contactTextField.setDisabledTextColor(new java.awt.Color(55, 96, 128));
        contactTextField.setOpaque(false);
        contactTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                contactTextFieldFocusGained(evt);
            }
        });
        contactTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactTextFieldActionPerformed(evt);
            }
        });

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        jLabel9.setText("Gender");

        genderComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "M", "F" }));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        jLabel8.setText("Date of Birth");

        nameSeparator5.setForeground(new java.awt.Color(0, 0, 0));

        nameSeparator6.setForeground(new java.awt.Color(0, 0, 0));

        nameSeparator9.setForeground(new java.awt.Color(0, 0, 0));

        emailTextField.setBackground(new java.awt.Color(55, 96, 128));
        emailTextField.setBorder(null);
        emailTextField.setCaretColor(new java.awt.Color(30, 59, 92));
        emailTextField.setDisabledTextColor(new java.awt.Color(55, 96, 128));
        emailTextField.setOpaque(false);
        emailTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                emailTextFieldFocusGained(evt);
            }
        });
        emailTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailTextFieldActionPerformed(evt);
            }
        });

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        jLabel12.setText("Email");

        nameSeparator8.setForeground(new java.awt.Color(0, 0, 0));

        emergencyContactJTextField.setBackground(new java.awt.Color(55, 96, 128));
        emergencyContactJTextField.setBorder(null);
        emergencyContactJTextField.setCaretColor(new java.awt.Color(30, 59, 92));
        emergencyContactJTextField.setDisabledTextColor(new java.awt.Color(55, 96, 128));
        emergencyContactJTextField.setOpaque(false);
        emergencyContactJTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                emergencyContactJTextFieldFocusGained(evt);
            }
        });
        emergencyContactJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emergencyContactJTextFieldActionPerformed(evt);
            }
        });

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        jLabel11.setText("Emergency Contact");

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        jLabel13.setText("Last Name");

        lastNameTextField.setBackground(new java.awt.Color(55, 96, 128));
        lastNameTextField.setBorder(null);
        lastNameTextField.setCaretColor(new java.awt.Color(30, 59, 92));
        lastNameTextField.setDisabledTextColor(new java.awt.Color(55, 96, 128));
        lastNameTextField.setOpaque(false);
        lastNameTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                lastNameTextFieldFocusGained(evt);
            }
        });
        lastNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastNameTextFieldActionPerformed(evt);
            }
        });

        nameSeparator11.setForeground(new java.awt.Color(0, 0, 0));

        saveButton.setBackground(new java.awt.Color(171, 204, 67));
        saveButton.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        updateButton.setBackground(new java.awt.Color(171, 204, 67));
        updateButton.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        updateButton.setText("Update");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        startUpdateButton.setBackground(new java.awt.Color(171, 204, 67));
        startUpdateButton.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        startUpdateButton.setText("Start Update");
        startUpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startUpdateButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(middleNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(add2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addressJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(zipTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(contactTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(startUpdateButton))
                    .addComponent(nameSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(nameSeparator4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                        .addComponent(nameSeparator7, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(nameSeparator2, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(nameSeparator3, javax.swing.GroupLayout.Alignment.LEADING)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(updateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(170, 170, 170))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(emergencyContactJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nameSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)
                            .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nameSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nameSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nameSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(jXDatePicker2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)
                            .addComponent(lastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nameSeparator11, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(genderComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(41, 41, 41))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(3, 3, 3)
                        .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(nameSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(3, 3, 3)
                        .addComponent(lastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(nameSeparator11, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(genderComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(nameSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jXDatePicker2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(middleNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nameSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addressJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(nameSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(6, 6, 6)
                                .addComponent(zipTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(nameSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel7)
                                .addGap(6, 6, 6)
                                .addComponent(contactTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(nameSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(6, 6, 6)
                                .addComponent(add2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(nameSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(122, 122, 122))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(nameSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(emergencyContactJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nameSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nameSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveButton)
                    .addComponent(startUpdateButton)
                    .addComponent(updateButton))
                .addGap(478, 478, 478))
        );

        jPanel2.setBackground(new java.awt.Color(23, 35, 51));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Create Patient");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1098, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(55, 96, 128));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        jLabel14.setText("Medications");

        medYes.setBackground(new java.awt.Color(55, 96, 128));
        medYes.setText("Yes");
        medYes.setBorder(null);

        medNo.setBackground(new java.awt.Color(55, 96, 128));
        medNo.setText("No");
        medNo.setBorder(null);

        anastheticYes.setBackground(new java.awt.Color(55, 96, 128));
        anastheticYes.setText("Yes");
        anastheticYes.setBorder(null);

        anastheticNo.setBackground(new java.awt.Color(55, 96, 128));
        anastheticNo.setText("No");
        anastheticNo.setBorder(null);

        jLabel17.setBackground(new java.awt.Color(255, 255, 255));
        jLabel17.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        jLabel17.setText("Anasthetic Allergy");

        jLabel21.setBackground(new java.awt.Color(255, 255, 255));
        jLabel21.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        jLabel21.setText("Other Allergies");

        otherYes.setBackground(new java.awt.Color(55, 96, 128));
        otherYes.setText("Yes");
        otherYes.setBorder(null);

        otherNo.setBackground(new java.awt.Color(55, 96, 128));
        otherNo.setText("No");
        otherNo.setBorder(null);

        jPanel6.setBackground(new java.awt.Color(93, 113, 128));

        jLabel29.setBackground(new java.awt.Color(55, 96, 128));
        jLabel29.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setText("Medical History");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                            .addComponent(otherYes))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(anastheticYes)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                        .addGap(55, 55, 55)
                        .addComponent(medYes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(anastheticNo)
                    .addComponent(otherNo)
                    .addComponent(medNo))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel14)
                                    .addComponent(medYes)
                                    .addComponent(medNo))
                                .addGap(31, 31, 31)
                                .addComponent(jLabel17))
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(anastheticYes)
                                .addComponent(anastheticNo)))
                        .addGap(36, 36, 36)
                        .addComponent(jLabel21))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(otherYes)
                        .addComponent(otherNo)))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        addMedicalHistoryButton.setBackground(new java.awt.Color(171, 204, 67));
        addMedicalHistoryButton.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        addMedicalHistoryButton.setText("Add");
        addMedicalHistoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMedicalHistoryButtonActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(55, 96, 128));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        jLabel22.setText("Policy Number");

        jLabel23.setText("Provider");

        jLabel24.setText("Begin Date");

        jLabel25.setText("Max Coverage");

        jLabel27.setText("End Date");

        beginDatePicker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beginDatePickerActionPerformed(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(93, 113, 128));

        jLabel26.setBackground(new java.awt.Color(55, 96, 128));
        jLabel26.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("Insurance Details");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(policyNumber))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(providerTxt))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(endDatePicker, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(beginDatePicker, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(maxCoverageTxt))))
                .addContainerGap())
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(policyNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(providerTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(maxCoverageTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(beginDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(endDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        addInsuranceButton.setBackground(new java.awt.Color(171, 204, 67));
        addInsuranceButton.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        addInsuranceButton.setText("Add Insurance");
        addInsuranceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addInsuranceButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 623, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(addMedicalHistoryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(addInsuranceButton, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(addMedicalHistoryButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(addInsuranceButton)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 918, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void nameTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameTextFieldFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTextFieldFocusGained

    private void nameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTextFieldActionPerformed

    private void add2TextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_add2TextFieldFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_add2TextFieldFocusGained

    private void add2TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add2TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_add2TextFieldActionPerformed

    private void addressJTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_addressJTextFieldFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_addressJTextFieldFocusGained

    private void addressJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressJTextFieldActionPerformed

    private void middleNameTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_middleNameTextFieldFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_middleNameTextFieldFocusGained

    private void middleNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_middleNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_middleNameTextFieldActionPerformed

    private void zipTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_zipTextFieldFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_zipTextFieldFocusGained

    private void zipTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zipTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_zipTextFieldActionPerformed

    private void contactTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_contactTextFieldFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_contactTextFieldFocusGained

    private void contactTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contactTextFieldActionPerformed

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        // TODO add your handling code here:

    }//GEN-LAST:event_jPanel1MouseDragged

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1MouseClicked

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1MousePressed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        String pFirstName = nameTextField.getText();
        String pMidName = middleNameTextField.getText();
        String pLastName = lastNameTextField.getText();
        String pAddr1 = addressJTextField.getText();
        String pAddr2 = add2TextField.getText();
        String pZip = zipTextField.getText();
        String contact = contactTextField.getText();
        String eContact = emergencyContactJTextField.getText();
        String email = emailTextField.getText();
        String gender = genderComboBox.getSelectedItem().toString();
        DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd hh:mm:ss");
        jXDatePicker2.setFormats(dateFormat);
        DateFormat sysDate = new SimpleDateFormat("yyyy-MM-dd hh:mm:ss");
        String bdate = sysDate.format(jXDatePicker2.getDate());
        String createPatient = "INSERT INTO [dbo].[patient]\n"
                + "           ([first_name]\n"
                + "           ,[middle_name]\n"
                + "           ,[last_name]\n"
                + "           ,[contact_number]\n"
                + "           ,[date_of_birth]\n"
                + "           ,[addressline1]\n"
                + "           ,[addressline2]\n"
                + "           ,[zip_code]\n"
                + "           ,[emergency_contact_number]\n"
                + "           ,[gender]\n"
                + "           ,[email_address])\n"
                + "     VALUES\n"
                + "           ('" + pFirstName + "','" + pMidName + "','" + pLastName + "','" + contact + "','" + bdate + "','" + pAddr1 + "',"
                + "'" + pAddr2 + "','" + pZip + "','" + eContact + "','" + gender + "','" + email + "')";


        String generatedColumns[] = {"patient_id"};
        try {
            statement.executeUpdate(createPatient, generatedColumns);
            ResultSet rs = statement.getGeneratedKeys();
            if (rs.next()) {
                long id = rs.getLong(1);
                pId = id;
            }
            JOptionPane.showMessageDialog(null, "Patient Created Successfully");
        } catch (SQLException ex) {
            Logger.getLogger(CreatePatientPanel.class.getName()).log(Level.SEVERE, null, ex);
        }

        nameTextField.setEnabled(false);
        middleNameTextField.setEnabled(false);
        lastNameTextField.setEnabled(false);
        addressJTextField.setEnabled(false);
        add2TextField.setEnabled(false);
        zipTextField.setEnabled(false);
        contactTextField.setEnabled(false);
        emergencyContactJTextField.setEnabled(false);
        emailTextField.setEnabled(false);
        genderComboBox.setEnabled(false);
        jXDatePicker2.setEnabled(false);

    }//GEN-LAST:event_saveButtonActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        // TODO add your handling code here:
        String pFirstName = nameTextField.getText();
        String pMidName = middleNameTextField.getText();
        String pLastName = nameTextField.getText();
        String pAddr1 = addressJTextField.getText();
        String pAddr2 = add2TextField.getText();
        String pZip = zipTextField.getText();
        String contact = contactTextField.getText();
        String eContact = emergencyContactJTextField.getText();
        String email = emailTextField.getText();
        String gender = genderComboBox.getSelectedItem().toString();
        DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd hh:mm:ss");
        jXDatePicker2.setFormats(dateFormat);
        DateFormat sysDate = new SimpleDateFormat("yyyy-MM-dd hh:mm:ss");
        String bdate = sysDate.format(jXDatePicker2.getDate());

        String updatePatient = "UPDATE [dbo].[patient]\n"
                + "   SET [first_name] = '" + pFirstName + "'\n"
                + "      ,[middle_name] = '" + pMidName + "'\n"
                + "      ,[last_name] ='" + pLastName + "'\n"
                + "      ,[contact_number] = '" + contact + "'\n"
                + "      ,[date_of_birth] = '" + bdate + "'\n"
                + "      ,[addressline1] = '" + pAddr1 + "'\n"
                + "      ,[addressline2] = '" + pAddr2 + "'\n"
                + "      ,[zip_code] = '" + pZip + "'\n"
                + "      ,[emergency_contact_number] = '" + eContact + "'\n"
                + "      ,[gender] = '" + gender + "'\n"
                + "      ,[email_address] = '" + email + "'";

        try {
            statement.executeUpdate(updatePatient);
            JOptionPane.showMessageDialog(null, "Patient Updated Successfully");
        } catch (SQLException ex) {
            Logger.getLogger(CreatePatientPanel.class.getName()).log(Level.SEVERE, null, ex);
        }

        nameTextField.setEnabled(false);
        middleNameTextField.setEnabled(false);
        lastNameTextField.setEnabled(false);
        addressJTextField.setEnabled(false);
        add2TextField.setEnabled(false);
        zipTextField.setEnabled(false);
        contactTextField.setEnabled(false);
        emergencyContactJTextField.setEnabled(false);
        emailTextField.setEnabled(false);
        genderComboBox.setEnabled(false);
        jXDatePicker2.setEnabled(false);
        startUpdateButton.setEnabled(true);
    }//GEN-LAST:event_updateButtonActionPerformed

    private void startUpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startUpdateButtonActionPerformed
        // TODO add your handling code here:
        startUpdateButton.setEnabled(false);
        nameTextField.setEnabled(true);
        middleNameTextField.setEnabled(true);
        lastNameTextField.setEnabled(true);
        addressJTextField.setEnabled(true);
        add2TextField.setEnabled(true);
        zipTextField.setEnabled(true);
        contactTextField.setEnabled(true);
        emergencyContactJTextField.setEnabled(true);
        emailTextField.setEnabled(true);
        genderComboBox.setEnabled(true);
        jXDatePicker2.setEnabled(true);
        updateButton.setEnabled(true);
    }//GEN-LAST:event_startUpdateButtonActionPerformed

    private void lastNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastNameTextFieldActionPerformed

    private void lastNameTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lastNameTextFieldFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_lastNameTextFieldFocusGained

    private void emergencyContactJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emergencyContactJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emergencyContactJTextFieldActionPerformed

    private void emergencyContactJTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emergencyContactJTextFieldFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_emergencyContactJTextFieldFocusGained

    private void emailTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailTextFieldActionPerformed

    private void emailTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailTextFieldFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_emailTextFieldFocusGained

    private void addMedicalHistoryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMedicalHistoryButtonActionPerformed
        // TODO add your handling code here:
        
        int med = 0;
        int anasthetic = 0;
        int other = 0;
       
        if (anastheticYes.isSelected()) {
            anasthetic = 1;
        } else {
            anasthetic = 0;
        }

        if (medYes.isSelected()) {
            med = 1;
        } else {
            med = 0;
        }

        if (otherYes.isSelected()) {
            other = 1;
        } else {
            other = 0;
        }


        String saveMedicalHistory = "INSERT INTO [dbo].[medical_history]\n"
                + "           ([medications]\n"
                + "           ,[patient_id]\n"
                + "           ,[anaesthetic_allergy]\n"
                + "           ,[other_allergies])\n"
                + "     VALUES\n"
                + "           ('" + med + "'\n"
                + "            ,'" + pId + "'\n"
                + "           ,'" + anasthetic + "'\n"
                + "           ,'" + other + "')";

        try {
            statement.executeUpdate(saveMedicalHistory);
            JOptionPane.showMessageDialog(null, "Medical History added successfully");
        } catch (SQLException ex) {
            Logger.getLogger(CreatePatientPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_addMedicalHistoryButtonActionPerformed

    private void addInsuranceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addInsuranceButtonActionPerformed
        // TODO add your handling code here:

        String poilicyNumber = policyNumber.getText();
        String provider = providerTxt.getText();
        int maxCoverage = Integer.parseInt(maxCoverageTxt.getText());
        String subscribers = zipTextField.getText();
        // DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd hh:mm:ss");
        //beginDatePicker.setFormats(dateFormat);
        DateFormat sysDate = new SimpleDateFormat("yyyy-MM-dd hh:mm:ss");
        String beginDate = sysDate.format(beginDatePicker.getDate());
        String endDate = sysDate.format(endDatePicker.getDate());

        String createInsurance = "INSERT INTO [dbo].[insurance]\n"
                + "           ([policy_number]\n"
                + "           ,[provider]\n"
                + "           ,[max_coverage]\n"
                + "           ,[patient_id]\n"
                + "           ,[begin_date]\n"
                + "           ,[end_date])\n"
                + "     VALUES\n"
                + "           ('" + poilicyNumber + "','" + provider + "','" + maxCoverage + "','" + pId
                + "','" + beginDate + "','" + endDate + "')";
        
        try {
            statement.executeUpdate(createInsurance);
            JOptionPane.showMessageDialog(null, "Insurance Details added successfully");
        } catch (SQLException ex) {
            Logger.getLogger(CreatePatientPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_addInsuranceButtonActionPerformed

    private void beginDatePickerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beginDatePickerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_beginDatePickerActionPerformed

    private void populateDefault() throws SQLException {

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField add2TextField;
    private javax.swing.JButton addInsuranceButton;
    private javax.swing.JButton addMedicalHistoryButton;
    private javax.swing.JTextField addressJTextField;
    private javax.swing.JRadioButton anastheticNo;
    private javax.swing.JRadioButton anastheticYes;
    private org.jdesktop.swingx.JXDatePicker beginDatePicker;
    private javax.swing.JTextField contactTextField;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JTextField emergencyContactJTextField;
    private org.jdesktop.swingx.JXDatePicker endDatePicker;
    private javax.swing.JComboBox genderComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private org.jdesktop.swingx.JXDatePicker jXDatePicker2;
    private javax.swing.JTextField lastNameTextField;
    private javax.swing.JTextField maxCoverageTxt;
    private javax.swing.JRadioButton medNo;
    private javax.swing.JRadioButton medYes;
    private javax.swing.JTextField middleNameTextField;
    private javax.swing.JSeparator nameSeparator;
    private javax.swing.JSeparator nameSeparator1;
    private javax.swing.JSeparator nameSeparator11;
    private javax.swing.JSeparator nameSeparator2;
    private javax.swing.JSeparator nameSeparator3;
    private javax.swing.JSeparator nameSeparator4;
    private javax.swing.JSeparator nameSeparator5;
    private javax.swing.JSeparator nameSeparator6;
    private javax.swing.JSeparator nameSeparator7;
    private javax.swing.JSeparator nameSeparator8;
    private javax.swing.JSeparator nameSeparator9;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JRadioButton otherNo;
    private javax.swing.JRadioButton otherYes;
    private javax.swing.JTextField policyNumber;
    private javax.swing.JTextField providerTxt;
    private javax.swing.JButton saveButton;
    private javax.swing.JButton startUpdateButton;
    private javax.swing.JButton updateButton;
    private javax.swing.JTextField zipTextField;
    // End of variables declaration//GEN-END:variables

}
