/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.Admin;

import java.awt.CardLayout;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author apoorva
 */
public class DoctorPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageEnterpriseJPanel
     */
    private Statement statement;
    private JPanel userProcessContainer;
    private Connection connection;
    private long pId;
    private Integer doctor_id;

    public DoctorPanel(Statement statement, JPanel userProcessContainer, Connection connection, Integer doctor_id) throws SQLException {
        initComponents();
        this.statement = statement;
        this.connection = connection;
        this.doctor_id = doctor_id;
        this.userProcessContainer = userProcessContainer;

        pictureLabel.setSize(107, 133);
        populateFields();
        populateTable();

    }
    
    private void populateTable() throws SQLException {
        DefaultTableModel model = (DefaultTableModel) appointmentTable.getModel();
        model.setRowCount(0);
        String getAppointments = "select appointment_id,last_name+','+' '+first_name as 'Patient Name',room_number,start_time,end_time,status from appointment\n"
                + "join patient on appointment.patient_id = patient.patient_id where dentist_id = '" + doctor_id + "'";
        ResultSet rs = statement.executeQuery(getAppointments);
        while (rs.next()) {
            model.addRow(new Object[]{rs.getString(1), rs.getString(2), rs.getString(3), rs.getString(4) + rs.getString(5), rs.getString(6)});
        }
    }
    private void populateFields() {
        try {

            statement = connection.createStatement();
            String doctorPhoto = "select doctor_Photo from doctor where doctor_id = '" + doctor_id + "'";
            String doctorDetails = "select first_name,middle_name,last_name,contact_number from doctor where doctor_id ='" + doctor_id + "'";
            String licenseDetails = "select license_number,authority,expiry_date from doctor_license where doctor_id ='" + doctor_id + "'";
            ResultSet rs = statement.executeQuery(doctorPhoto);
            while (rs.next()) {
                BufferedImage im = ImageIO.read(rs.getBinaryStream("doctor_Photo"));
                Image dimg = im.getScaledInstance(pictureLabel.getWidth(), pictureLabel.getHeight(),
                        Image.SCALE_SMOOTH);
                pictureLabel.setIcon(new ImageIcon(dimg));
            }
            ResultSet rs1 = statement.executeQuery(doctorDetails);
            while (rs1.next()) {
                firstNameTextField.setText(rs1.getString(1));
                middleNameTextField.setText(rs1.getString(2));
                lastNameTextField.setText(rs1.getString(3));
                contactTextField.setText(rs1.getString(4));
            }
            ResultSet rs2 = statement.executeQuery(licenseDetails);
            while (rs2.next()) {
                licenseNumber.setText(rs2.getString(1));
                authority.setText(rs2.getString(2));
                expiryDate.setText(rs2.getString(3));
            }

        } catch (Exception err) {
            JOptionPane.showMessageDialog(this, err.getMessage());
        }
    }

    public ImageIcon ResizeImage(String ImagePath) {
        ImageIcon MyImage = new ImageIcon(ImagePath);
        Image img = MyImage.getImage();

        Image newImg = img.getScaledInstance(pictureLabel.getWidth(), pictureLabel.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImg);
        return image;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        firstNameTextField = new javax.swing.JTextField();
        nameSeparator = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        middleNameTextField = new javax.swing.JTextField();
        nameSeparator1 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        contactTextField = new javax.swing.JTextField();
        nameSeparator3 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        nameSeparator2 = new javax.swing.JSeparator();
        lastNameTextField = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        nameSeparator6 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        nameSeparator5 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        nameSeparator4 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        authority = new javax.swing.JTextField();
        licenseNumber = new javax.swing.JTextField();
        expiryDate = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        pictureLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        appointmentTable = new javax.swing.JTable();
        proceedButton = new javax.swing.JButton();
        cancelAppointment = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(55, 96, 128));
        setPreferredSize(new java.awt.Dimension(1000, 617));

        jPanel2.setBackground(new java.awt.Color(55, 96, 128));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        jLabel2.setText("First Name");

        firstNameTextField.setEditable(false);
        firstNameTextField.setBackground(new java.awt.Color(55, 96, 128));
        firstNameTextField.setBorder(null);
        firstNameTextField.setCaretColor(new java.awt.Color(55, 96, 128));
        firstNameTextField.setDisabledTextColor(new java.awt.Color(55, 96, 128));
        firstNameTextField.setOpaque(false);
        firstNameTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                firstNameTextFieldFocusGained(evt);
            }
        });
        firstNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNameTextFieldActionPerformed(evt);
            }
        });

        nameSeparator.setForeground(new java.awt.Color(0, 0, 0));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        jLabel3.setText("Middle Name");

        middleNameTextField.setEditable(false);
        middleNameTextField.setBackground(new java.awt.Color(55, 96, 128));
        middleNameTextField.setBorder(null);
        middleNameTextField.setCaretColor(new java.awt.Color(30, 59, 92));
        middleNameTextField.setDisabledTextColor(new java.awt.Color(55, 96, 128));
        middleNameTextField.setOpaque(false);
        middleNameTextField.setSelectedTextColor(new java.awt.Color(55, 96, 128));
        middleNameTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                middleNameTextFieldFocusGained(evt);
            }
        });
        middleNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                middleNameTextFieldActionPerformed(evt);
            }
        });

        nameSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        jLabel6.setText("Last Name");

        contactTextField.setEditable(false);
        contactTextField.setBackground(new java.awt.Color(55, 96, 128));
        contactTextField.setBorder(null);
        contactTextField.setCaretColor(new java.awt.Color(30, 59, 92));
        contactTextField.setDisabledTextColor(new java.awt.Color(55, 96, 128));
        contactTextField.setOpaque(false);
        contactTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                contactTextFieldFocusGained(evt);
            }
        });
        contactTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactTextFieldActionPerformed(evt);
            }
        });

        nameSeparator3.setForeground(new java.awt.Color(0, 0, 0));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        jLabel5.setText("Contact");

        nameSeparator2.setForeground(new java.awt.Color(0, 0, 0));

        lastNameTextField.setEditable(false);
        lastNameTextField.setBackground(new java.awt.Color(55, 96, 128));
        lastNameTextField.setBorder(null);
        lastNameTextField.setCaretColor(new java.awt.Color(30, 59, 92));
        lastNameTextField.setDisabledTextColor(new java.awt.Color(55, 96, 128));
        lastNameTextField.setOpaque(false);
        lastNameTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                lastNameTextFieldFocusGained(evt);
            }
        });
        lastNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastNameTextFieldActionPerformed(evt);
            }
        });

        nameSeparator6.setForeground(new java.awt.Color(0, 0, 0));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        jLabel8.setText("Epiry Date");

        nameSeparator5.setForeground(new java.awt.Color(0, 0, 0));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        jLabel7.setText("Authority");

        nameSeparator4.setForeground(new java.awt.Color(0, 0, 0));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        jLabel4.setText("License Number");

        authority.setEditable(false);
        authority.setBorder(null);
        authority.setCaretColor(new java.awt.Color(30, 59, 92));
        authority.setDisabledTextColor(new java.awt.Color(55, 96, 128));
        authority.setOpaque(false);
        authority.setSelectedTextColor(new java.awt.Color(55, 96, 128));
        authority.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                authorityFocusGained(evt);
            }
        });
        authority.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                authorityActionPerformed(evt);
            }
        });

        licenseNumber.setEditable(false);
        licenseNumber.setBorder(null);
        licenseNumber.setCaretColor(new java.awt.Color(30, 59, 92));
        licenseNumber.setDisabledTextColor(new java.awt.Color(55, 96, 128));
        licenseNumber.setOpaque(false);
        licenseNumber.setSelectedTextColor(new java.awt.Color(55, 96, 128));
        licenseNumber.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                licenseNumberFocusGained(evt);
            }
        });
        licenseNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                licenseNumberActionPerformed(evt);
            }
        });

        expiryDate.setEditable(false);
        expiryDate.setBorder(null);
        expiryDate.setCaretColor(new java.awt.Color(30, 59, 92));
        expiryDate.setDisabledTextColor(new java.awt.Color(55, 96, 128));
        expiryDate.setOpaque(false);
        expiryDate.setSelectedTextColor(new java.awt.Color(55, 96, 128));
        expiryDate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                expiryDateFocusGained(evt);
            }
        });
        expiryDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expiryDateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel7)
                        .addComponent(nameSeparator5)
                        .addComponent(nameSeparator6)
                        .addComponent(jLabel4)
                        .addComponent(nameSeparator4)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(authority, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(licenseNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(expiryDate, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(212, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(licenseNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nameSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel7)
                .addGap(3, 3, 3)
                .addComponent(authority, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nameSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jLabel8)
                .addGap(4, 4, 4)
                .addComponent(expiryDate, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nameSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pictureLabel.setBackground(new java.awt.Color(255, 255, 255));
        pictureLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pictureLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pictureLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pictureLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel3)
                                .addComponent(middleNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(nameSeparator1)
                                .addComponent(nameSeparator2)
                                .addComponent(nameSeparator3)
                                .addComponent(jLabel2)
                                .addComponent(firstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(nameSeparator)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(contactTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(3, 3, 3)
                .addComponent(firstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nameSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel3)
                .addGap(3, 3, 3)
                .addComponent(middleNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nameSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jLabel6)
                .addGap(1, 1, 1)
                .addComponent(lastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nameSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(1, 1, 1)
                .addComponent(contactTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nameSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        appointmentTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Appointment Id", "Patient Name", "Room Number", "Time", "Status"
            }
        ));
        appointmentTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(appointmentTable);

        proceedButton.setBackground(new java.awt.Color(171, 204, 67));
        proceedButton.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        proceedButton.setText("Proceed");
        proceedButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proceedButtonActionPerformed(evt);
            }
        });

        cancelAppointment.setBackground(new java.awt.Color(171, 204, 67));
        cancelAppointment.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        cancelAppointment.setText("Cancel");
        cancelAppointment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelAppointmentActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(23, 35, 51));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Doctor Home Page");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1098, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(proceedButton)
                        .addGap(185, 185, 185)
                        .addComponent(cancelAppointment)
                        .addGap(78, 78, 78)))
                .addGap(111, 111, 111))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(198, 198, 198)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(proceedButton)
                    .addComponent(cancelAppointment))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void contactTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contactTextFieldActionPerformed

    private void contactTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_contactTextFieldFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_contactTextFieldFocusGained

    private void middleNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_middleNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_middleNameTextFieldActionPerformed

    private void middleNameTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_middleNameTextFieldFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_middleNameTextFieldFocusGained

    private void firstNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstNameTextFieldActionPerformed

    private void firstNameTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_firstNameTextFieldFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_firstNameTextFieldFocusGained

    private void proceedButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proceedButtonActionPerformed
        // TODO add your handling code here:

        int selectedRow = appointmentTable.getSelectedRow();

        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row to Process", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String appointment = appointmentTable.getValueAt(selectedRow, 0).toString();

        TreatmentPanel treatment = null;
        try {
            treatment = new TreatmentPanel(statement, userProcessContainer, connection, appointment);
        } catch (SQLException ex) {
            Logger.getLogger(DoctorPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        userProcessContainer.add("DoctorPanel", treatment);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_proceedButtonActionPerformed

    private void cancelAppointmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelAppointmentActionPerformed
        // TODO add your handling code here:
        
        int selectedRow = appointmentTable.getSelectedRow();
        String appointmentId = appointmentTable.getValueAt(selectedRow, 0).toString();
        String cancelAppointment = "UPDATE [dbo].[appointment]\n"
                + "   SET \n"
                + "      [status] = 'Cancelled'\n"
                + " WHERE appointment_id = '" + appointmentId + "'";
        
        try {
            statement.executeUpdate(cancelAppointment);
            JOptionPane.showMessageDialog(null,"Appointment Cancelled");
            populateTable();
        } catch (SQLException ex) {
            Logger.getLogger(DoctorPanel.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_cancelAppointmentActionPerformed

    private void lastNameTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lastNameTextFieldFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_lastNameTextFieldFocusGained

    private void lastNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastNameTextFieldActionPerformed

    private void authorityFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_authorityFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_authorityFocusGained

    private void authorityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_authorityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_authorityActionPerformed

    private void licenseNumberFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_licenseNumberFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_licenseNumberFocusGained

    private void licenseNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_licenseNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_licenseNumberActionPerformed

    private void expiryDateFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_expiryDateFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_expiryDateFocusGained

    private void expiryDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expiryDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_expiryDateActionPerformed

    private void populateDefault() throws SQLException {

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable appointmentTable;
    private javax.swing.JTextField authority;
    private javax.swing.JButton cancelAppointment;
    private javax.swing.JTextField contactTextField;
    private javax.swing.JTextField expiryDate;
    private javax.swing.JTextField firstNameTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lastNameTextField;
    private javax.swing.JTextField licenseNumber;
    private javax.swing.JTextField middleNameTextField;
    private javax.swing.JSeparator nameSeparator;
    private javax.swing.JSeparator nameSeparator1;
    private javax.swing.JSeparator nameSeparator2;
    private javax.swing.JSeparator nameSeparator3;
    private javax.swing.JSeparator nameSeparator4;
    private javax.swing.JSeparator nameSeparator5;
    private javax.swing.JSeparator nameSeparator6;
    private javax.swing.JLabel pictureLabel;
    private javax.swing.JButton proceedButton;
    // End of variables declaration//GEN-END:variables

}
