/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.Admin;

import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author apoorva
 */
public class EquipmentsPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageEnterpriseJPanel
     */
    private Statement statement;
    private JPanel userProcessContainer;
    private long pId;
    private String appointmentId ;
    private Connection connection;

    public EquipmentsPanel(Statement statement, JPanel userProcessContainer, Connection connection) throws SQLException {
        initComponents();
         this.statement = statement;
         this.connection = connection;
         this.appointmentId = appointmentId;
         roomComboBox.removeAllItems();
         populateEquipmentTable();
         populateSuppliesTable();
          String getRoom = "select room_number from room" ;
            ResultSet room_result = statement.executeQuery(getRoom);
      
       while (room_result.next()) {
                  
         roomComboBox.addItem(room_result.getString(1));
        }
         

    }
    
    private void populateSuppliesTable() throws SQLException {
        DefaultTableModel model = (DefaultTableModel) suppliesTable.getModel();

        CallableStatement stmt = null;
        //String getTreatments = "  select * from [Supplies Availability]";
        stmt = connection.prepareCall("select * from [Supplies]");
        ResultSet rs = stmt.executeQuery();
        while (rs.next()) {
            model.addRow(new Object[]{
                rs.getString(1),
                rs.getString(2),});
        }
    }
private void populateEquipmentTable() throws SQLException{
    
DefaultTableModel model = (DefaultTableModel) equipmentTable.getModel();
        model.setRowCount(0);
         
        String getTreatments = "  select * from equipment";
        ResultSet rs = statement.executeQuery(getTreatments);
        while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getString(1), 
                    rs.getString(2),
                     rs.getString(3),
                      rs.getString(4),
                       rs.getString(5),
                });
            }
}
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        equipmentTable = new javax.swing.JTable();
        addEquipmentButton = new javax.swing.JButton();
        saveEquipButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        equipmentName = new javax.swing.JTextField();
        nameSeparator = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        mainatainanceDatePicker = new org.jdesktop.swingx.JXDatePicker();
        nameSeparator5 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        warrantyDatePicker = new org.jdesktop.swingx.JXDatePicker();
        nameSeparator6 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        purchaseDatePicker = new org.jdesktop.swingx.JXDatePicker();
        nameSeparator7 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        equipmentId = new javax.swing.JTextField();
        nameSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        nameSeparator2 = new javax.swing.JSeparator();
        roomComboBox = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        suppliesTable = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        deleteButton = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(55, 96, 128));
        setPreferredSize(new java.awt.Dimension(1100, 617));

        equipmentTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Equipment Name", "Maintainance Due Date", "Warranty End Date", "Purchase Date", "Equipment Id"
            }
        ));
        equipmentTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(equipmentTable);
        if (equipmentTable.getColumnModel().getColumnCount() > 0) {
            equipmentTable.getColumnModel().getColumn(2).setHeaderValue("Warranty End Date");
            equipmentTable.getColumnModel().getColumn(3).setHeaderValue("Purchase Date");
            equipmentTable.getColumnModel().getColumn(4).setHeaderValue("Equipment Id");
        }

        addEquipmentButton.setText("Add");
        addEquipmentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addEquipmentButtonActionPerformed(evt);
            }
        });

        saveEquipButton.setText("Save");
        saveEquipButton.setEnabled(false);
        saveEquipButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveEquipButtonActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        jLabel2.setText("Equipment Name");

        equipmentName.setBackground(new java.awt.Color(55, 96, 128));
        equipmentName.setBorder(null);
        equipmentName.setCaretColor(new java.awt.Color(55, 96, 128));
        equipmentName.setDisabledTextColor(new java.awt.Color(55, 96, 128));
        equipmentName.setEnabled(false);
        equipmentName.setOpaque(false);
        equipmentName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                equipmentNameFocusGained(evt);
            }
        });
        equipmentName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equipmentNameActionPerformed(evt);
            }
        });

        nameSeparator.setForeground(new java.awt.Color(0, 0, 0));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        jLabel8.setText("Maintainance Due Date");

        mainatainanceDatePicker.setEnabled(false);

        nameSeparator5.setForeground(new java.awt.Color(0, 0, 0));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        jLabel9.setText("Warranty End Date");

        warrantyDatePicker.setEnabled(false);

        nameSeparator6.setForeground(new java.awt.Color(0, 0, 0));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        jLabel10.setText("Purchase Date");

        purchaseDatePicker.setEnabled(false);

        nameSeparator7.setForeground(new java.awt.Color(0, 0, 0));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        jLabel3.setText("Equipment Id");

        equipmentId.setBackground(new java.awt.Color(55, 96, 128));
        equipmentId.setBorder(null);
        equipmentId.setCaretColor(new java.awt.Color(55, 96, 128));
        equipmentId.setDisabledTextColor(new java.awt.Color(55, 96, 128));
        equipmentId.setEnabled(false);
        equipmentId.setOpaque(false);
        equipmentId.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                equipmentIdFocusGained(evt);
            }
        });
        equipmentId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equipmentIdActionPerformed(evt);
            }
        });

        nameSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        jLabel4.setText("Room Id");

        nameSeparator2.setForeground(new java.awt.Color(0, 0, 0));

        roomComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        roomComboBox.setEnabled(false);

        suppliesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Supplies Name", "Number of Units"
            }
        ));
        suppliesTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(suppliesTable);

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Low Supplies");

        deleteButton.setText("Delete");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(23, 35, 51));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Equipments and Supplies Management");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1102, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel2)
                        .addComponent(equipmentName, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                        .addComponent(jLabel8)
                        .addComponent(jLabel9)
                        .addComponent(jLabel10)
                        .addComponent(purchaseDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)
                        .addComponent(equipmentId, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addComponent(nameSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                        .addComponent(roomComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(nameSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                        .addComponent(nameSeparator6)
                        .addComponent(nameSeparator5)
                        .addComponent(nameSeparator, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                        .addComponent(nameSeparator7))
                    .addComponent(mainatainanceDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(warrantyDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(saveEquipButton, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addEquipmentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62))
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel2)
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(equipmentName, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(3, 3, 3)
                                .addComponent(nameSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel8)
                                .addGap(15, 15, 15)
                                .addComponent(mainatainanceDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(16, 16, 16)
                                .addComponent(nameSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(addEquipmentButton)
                                .addGap(58, 58, 58)
                                .addComponent(saveEquipButton)))
                        .addGap(4, 4, 4)
                        .addComponent(jLabel9)
                        .addGap(15, 15, 15)
                        .addComponent(warrantyDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(nameSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(deleteButton))
                        .addGap(7, 7, 7)
                        .addComponent(jLabel10))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(purchaseDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(jLabel5))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nameSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(equipmentId, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(nameSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(jLabel4)
                        .addGap(7, 7, 7)
                        .addComponent(roomComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nameSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void equipmentNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_equipmentNameFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_equipmentNameFocusGained

    private void equipmentNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equipmentNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_equipmentNameActionPerformed

    private void equipmentIdFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_equipmentIdFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_equipmentIdFocusGained

    private void equipmentIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equipmentIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_equipmentIdActionPerformed

    private void saveEquipButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveEquipButtonActionPerformed
        // TODO add your handling code here:
        
        String equipName = equipmentName.getText();
        String equipId = equipmentId.getText();
        DateFormat sysDate = new SimpleDateFormat("yyyy-MM-dd hh:mm:ss");
        String maintainance = sysDate.format(mainatainanceDatePicker.getDate());
        String warranty = sysDate.format(warrantyDatePicker.getDate());
        String purchase = sysDate.format(purchaseDatePicker.getDate());
        String roomNumber = roomComboBox.getSelectedItem().toString();
           String createEquipment = "INSERT INTO [dbo].[equipment]\n"
                + "           ([equipment_name]\n"
                + "           ,[maintenance_due_date]\n"
                + "           ,[warranty_end_date]\n"
                + "           ,[purchase_date]\n"
                + "           ,[equipment_id]\n"
                + "           ,[room_number])\n"
                + "     VALUES\n"
                + "           ('" + equipName + "','" + maintainance + "','" + warranty + "','" + purchase + "','" + equipId + "','" + roomNumber + "')";
           
        try {
            statement.executeUpdate(createEquipment);
            JOptionPane.showMessageDialog(null, "Equipment Added Successfully");
            populateEquipmentTable();
        addEquipmentButton.setEnabled(true);
        equipmentName.setEnabled(false);
        mainatainanceDatePicker.setEnabled(false);
        warrantyDatePicker.setEnabled(false);
        purchaseDatePicker.setEnabled(false);
        equipmentId.setEnabled(false);
        saveEquipButton.setEnabled(false);
        roomComboBox.setEnabled(false);
        } catch (SQLException ex) {
            Logger.getLogger(EquipmentsPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
            
    }//GEN-LAST:event_saveEquipButtonActionPerformed

    private void addEquipmentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addEquipmentButtonActionPerformed
        // TODO add your handling code here:
        addEquipmentButton.setEnabled(false);
        equipmentName.setEnabled(true);
        mainatainanceDatePicker.setEnabled(true);
        warrantyDatePicker.setEnabled(true);
        purchaseDatePicker.setEnabled(true);
        equipmentId.setEnabled(true);
        saveEquipButton.setEnabled(true);
        roomComboBox.setEnabled(true);
    }//GEN-LAST:event_addEquipmentButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // TODO add your handling code here:
        int column = 4;
        int row = equipmentTable.getSelectedRow();
        String value = equipmentTable.getModel().getValueAt(row, column).toString();
        
        String  deleteEquipment = "DELETE FROM equipment WHERE [equipment_id] = " + value + "";
        try {
            statement.executeUpdate(deleteEquipment);
           
            populateEquipmentTable();
            //int s = equipmentTable.getValueAt(ERROR, WIDTH);
        } catch (SQLException ex) {
            Logger.getLogger(EquipmentsPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_deleteButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addEquipmentButton;
    private javax.swing.JButton deleteButton;
    private javax.swing.JTextField equipmentId;
    private javax.swing.JTextField equipmentName;
    private javax.swing.JTable equipmentTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private org.jdesktop.swingx.JXDatePicker mainatainanceDatePicker;
    private javax.swing.JSeparator nameSeparator;
    private javax.swing.JSeparator nameSeparator1;
    private javax.swing.JSeparator nameSeparator2;
    private javax.swing.JSeparator nameSeparator5;
    private javax.swing.JSeparator nameSeparator6;
    private javax.swing.JSeparator nameSeparator7;
    private org.jdesktop.swingx.JXDatePicker purchaseDatePicker;
    private javax.swing.JComboBox<String> roomComboBox;
    private javax.swing.JButton saveEquipButton;
    private javax.swing.JTable suppliesTable;
    private org.jdesktop.swingx.JXDatePicker warrantyDatePicker;
    // End of variables declaration//GEN-END:variables

}
