/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.Admin;

import java.awt.CardLayout;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;


/**
 *
 * @author Vivek
 */
 
public class ManageAppointmentPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageEnterpriseJPanel
     */
     private Statement statement ;
     private JPanel userProcessContainer;
     private Connection connection;
    public ManageAppointmentPanel(Statement statement,JPanel userProcessContainer , Connection connection) throws SQLException {
        initComponents();
        this.statement = statement ;
        this.connection = connection;
        this.userProcessContainer = userProcessContainer;
        populateDefault();
    }
    
    private void populateDefault() throws SQLException {

        locationComboBox.removeAllItems();
        doctorComboBox.removeAllItems();
        roomComboBox.removeAllItems();
        patientComboBox.removeAllItems();

        String getLocation = "select addressline1 , location_id from location";
        ResultSet location_result = statement.executeQuery(getLocation);

        while (location_result.next()) {
            locationComboBox.addItem(location_result.getString(2).trim() + " - " + location_result.getString(1).trim());
        }

        String getDoctor = "select doctor_id , first_name , last_name from doctor";
        ResultSet doctor_result = statement.executeQuery(getDoctor);

        while (doctor_result.next()) {

            doctorComboBox.addItem(doctor_result.getString(1).trim() + " - "
                    + doctor_result.getString(2).trim() + " "
                    + doctor_result.getString(3).trim());
        }

    }
     
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        btn_exit = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        patientComboBox = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        doctorComboBox = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        locationComboBox = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        roomComboBox = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        jXDatePicker2 = new org.jdesktop.swingx.JXDatePicker();
        jLabel13 = new javax.swing.JLabel();
        timeComboBox = new javax.swing.JComboBox<>();
        verifyButton = new javax.swing.JButton();
        bookAppointment = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        firstNameTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        contactTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        searchButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        lastNameTextField = new javax.swing.JTextField();
        nameSeparator = new javax.swing.JSeparator();
        nameSeparator1 = new javax.swing.JSeparator();
        nameSeparator2 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextArea = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(55, 96, 128));

        jPanel5.setBackground(new java.awt.Color(55, 96, 128));

        btn_exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_exitMousePressed(evt);
            }
        });

        patientComboBox.setBackground(new java.awt.Color(71, 120, 197));
        patientComboBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                patientComboBoxMouseEntered(evt);
            }
        });

        jLabel6.setText("Patient Name");

        jLabel9.setText("Doctor Name");

        doctorComboBox.setBackground(new java.awt.Color(71, 120, 197));
        doctorComboBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                doctorComboBoxMouseEntered(evt);
            }
        });

        jLabel14.setText("Location");

        locationComboBox.setBackground(new java.awt.Color(71, 120, 197));
        locationComboBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                locationComboBoxMouseEntered(evt);
            }
        });
        locationComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                locationComboBoxActionPerformed(evt);
            }
        });

        jLabel15.setText("Room");

        roomComboBox.setBackground(new java.awt.Color(71, 120, 197));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Date ");

        jXDatePicker2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jXDatePicker2MousePressed(evt);
            }
        });
        jXDatePicker2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jXDatePicker2ActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Time");

        timeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1" }));

        verifyButton.setBackground(new java.awt.Color(171, 204, 67));
        verifyButton.setText("Verify");
        verifyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verifyButtonActionPerformed(evt);
            }
        });

        bookAppointment.setBackground(new java.awt.Color(171, 204, 67));
        bookAppointment.setText("Book");
        bookAppointment.setEnabled(false);
        bookAppointment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookAppointmentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(verifyButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bookAppointment, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE))
                        .addGap(74, 74, 74))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(10, 10, 10)
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel5Layout.createSequentialGroup()
                                                .addGap(129, 129, 129)
                                                .addComponent(btn_exit))
                                            .addComponent(patientComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(10, 10, 10)
                                        .addComponent(doctorComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(locationComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(10, 10, 10)
                                        .addComponent(roomComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jXDatePicker2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(timeComboBox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(5, 5, 5)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(20, 20, 20)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(btn_exit, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(patientComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(doctorComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(locationComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(roomComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel16)))
                .addGap(11, 11, 11)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(timeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jXDatePicker2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(verifyButton)
                .addGap(26, 26, 26)
                .addComponent(bookAppointment, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        jButton1.setBackground(new java.awt.Color(171, 204, 67));
        jButton1.setText("Create Patient");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel7.setBackground(new java.awt.Color(55, 96, 128));
        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        firstNameTextField.setBackground(new java.awt.Color(55, 96, 128));
        firstNameTextField.setForeground(new java.awt.Color(255, 255, 255));
        firstNameTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        firstNameTextField.setBorder(null);
        firstNameTextField.setCaretColor(new java.awt.Color(255, 255, 255));
        firstNameTextField.setPreferredSize(new java.awt.Dimension(2, 20));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("First Name");

        contactTextField.setBackground(new java.awt.Color(55, 96, 128));
        contactTextField.setForeground(new java.awt.Color(255, 255, 255));
        contactTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        contactTextField.setBorder(null);
        contactTextField.setCaretColor(new java.awt.Color(255, 255, 255));
        contactTextField.setPreferredSize(new java.awt.Dimension(2, 20));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Contact");

        searchButton.setText("Search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Last Name");

        lastNameTextField.setBackground(new java.awt.Color(55, 96, 128));
        lastNameTextField.setForeground(new java.awt.Color(255, 255, 255));
        lastNameTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        lastNameTextField.setBorder(null);
        lastNameTextField.setCaretColor(new java.awt.Color(255, 255, 255));
        lastNameTextField.setPreferredSize(new java.awt.Dimension(2, 20));

        nameSeparator.setForeground(new java.awt.Color(0, 0, 0));

        nameSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        nameSeparator2.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(firstNameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nameSeparator2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nameSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nameSeparator, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchButton, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                    .addComponent(lastNameTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(contactTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 15, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(firstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(nameSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nameSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contactTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nameSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(searchButton)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(23, 35, 51));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Manage Appointment");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1098, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        TextArea.setBackground(new java.awt.Color(0, 0, 0));
        TextArea.setColumns(20);
        TextArea.setForeground(new java.awt.Color(0, 204, 0));
        TextArea.setRows(5);
        jScrollPane1.setViewportView(TextArea);

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Booking Details");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(51, 51, 51)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(jButton1))
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void verifyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verifyButtonActionPerformed
        // TODO add your handling code here:
        verifyButton.setEnabled(false);
        try{
            String patient = patientComboBox.getSelectedItem().toString();
            String patientName = patient.substring(patient.indexOf("-") + 2).trim();

            String doctor = doctorComboBox.getSelectedItem().toString();
            String doctorName = doctor.substring(doctor.indexOf("-")+2);

            String location = locationComboBox.getSelectedItem().toString();
            String locationID = location.substring(0, location.indexOf("-")).trim();

            System.out.println(locationID);
            String getLocDetails = "select addressline1 ,addressline2 , zip_code ,"
            + " contact_number  from location where location_id = '" + locationID + "'";

            System.out.println(getLocDetails);

            ResultSet loc_result = statement.executeQuery(getLocDetails);

            while (loc_result.next()) {
                TextArea.append("Appointment Details \n"
                    + "Patient Name :- " + patientName + "\n"
                    + "Doctor Name :- " +  doctorName + "\n"
                    + "Date :- "         + jXDatePicker2.getDate() + "\n"
                    + "Time :-"         + timeComboBox.getSelectedItem().toString() + "\n"
                    + "Address:- \n"       + loc_result.getString(1).trim() +" " +  loc_result.getString(2).trim()  + "\n"
                    + "Zip Code :- "      + loc_result.getString(3).trim()     + "\n"
                    + "Contact :- "       + loc_result.getString(4).trim()

                );
            }
            bookAppointment.setEnabled(true);
        } catch (SQLException e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_verifyButtonActionPerformed

    private void jXDatePicker2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jXDatePicker2ActionPerformed
        // TODO add your handling code here:
        try{
            timeComboBox.removeAllItems();
            int doctorID = doctorComboBox.getSelectedIndex() + 1;

            DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
            String date = dateFormat.format(jXDatePicker2.getDate());

            String getDoctorSchedule =
            "SELECT  [Slot1],[Slot2],[Slot3],[Slot4],[Slot5],[Slot6],[Slot7],[Slot8],[date],"
            + "[doctor_id] FROM doctor_schedule where doctor_id = " + doctorID + "AND date = '" + date +"'" ;

            ResultSet time_result = statement.executeQuery(getDoctorSchedule);

            while (time_result.next()) {

                //roomComboBox.addItem("Room Number - " +time_result.getString(1).trim());

                if (time_result.getString(1).equals("0")) {
                    timeComboBox.addItem("10:00-10:30");
                }

                if (time_result.getString(2).equals("0")) {
                    timeComboBox.addItem("10:30-11:00");
                }

                if (time_result.getString(3).equals("0")) {
                    timeComboBox.addItem("11:00-11:30");
                }

                if (time_result.getString(4).equals("0")) {
                    timeComboBox.addItem("11:30-12:00");
                }

                if (time_result.getString(5).equals("0")) {
                    timeComboBox.addItem("13:00-13:30");
                }

                if (time_result.getString(6).equals("0")) {
                    timeComboBox.addItem("13:30-14:00");
                }

                if (time_result.getString(7).equals("0")) {
                    timeComboBox.addItem("14:00-14:30");
                }

                if (time_result.getString(8).equals("0")) {
                    timeComboBox.addItem("14:30-15:00");
                }

            }
        } catch (SQLException e){
            e.printStackTrace();
        }

    }//GEN-LAST:event_jXDatePicker2ActionPerformed

    private void jXDatePicker2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jXDatePicker2MousePressed
        // TODO add your handling code here:

    }//GEN-LAST:event_jXDatePicker2MousePressed

    private void locationComboBoxMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_locationComboBoxMouseEntered
        // TODO add your handling code here:

        int location = locationComboBox.getSelectedIndex() + 1;
        try {
            roomComboBox.removeAllItems();

            String getroom = "select  room_number from room where location_id = " + location;

            ResultSet room_result = statement.executeQuery(getroom);

            while (room_result.next()) {
                roomComboBox.addItem(room_result.getString(1).trim());
            }

        } catch (SQLException e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_locationComboBoxMouseEntered

    private void doctorComboBoxMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_doctorComboBoxMouseEntered
        // TODO add your handling code here:

    }//GEN-LAST:event_doctorComboBoxMouseEntered

    private void patientComboBoxMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_patientComboBoxMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_patientComboBoxMouseEntered

    private void btn_exitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_exitMousePressed
        // TODO add your handling code here:

        System.exit(0);
    }//GEN-LAST:event_btn_exitMousePressed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        // TODO add your handling code here:
        try{
            if(lastNameTextField.getText().equals("")){
            patientComboBox.removeAllItems();

            String getPatient = "select  patient_id ,first_name , last_name from patient where first_name LIKE '" +
            firstNameTextField.getText() + "%' AND contact_number LIKE '" + contactTextField.getText() +"%'" ;

            ResultSet patient_result = statement.executeQuery(getPatient);

            while (patient_result.next()) {

                patientComboBox.addItem(patient_result.getString(1).trim()+ " - "
                    + patient_result.getString(2).trim() + " "
                    + patient_result.getString(3).trim() );
            }
            }
            else{
                patientComboBox.removeAllItems();
                String s1 = lastNameTextField.getText();
                ArrayList<String> list = new ArrayList<String>();
                String lastName = "select last_name,first_name from patient";
                 ResultSet patient_lastName_result = statement.executeQuery(lastName);
                 while (patient_lastName_result.next()) {
                     
                     String s2 = patient_lastName_result.getString(1);
                        list.add(s2);
                     }
                 
                 for(String s2:list){
                    String soundexLastName = "select soundex('" + s1 + "'),soundex('" + s2 + "')";
                     ResultSet soundexSet = statement.executeQuery(soundexLastName);
                     
                     while (soundexSet.next()) {
                     if(soundexSet.getString(1).equals(soundexSet.getString(2))){                         
                         patientComboBox.addItem(s2);
                     }
                     }
                 }
            }
        } catch (SQLException e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_searchButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        CreatePatientPanel createPatient = new CreatePatientPanel(statement,userProcessContainer);
        userProcessContainer.add("CreatePatientPanel",createPatient);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void bookAppointmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookAppointmentActionPerformed
        // TODO add your handling code here:
        
           try {
            bookAppointment.setEnabled(false);
            CallableStatement stmt = null;
            String patient = patientComboBox.getSelectedItem().toString();
            String patientID = patient.substring(0, patient.indexOf("-")).trim();

            String doctor = doctorComboBox.getSelectedItem().toString();
            String doctorID = doctor.substring(0, doctor.indexOf("-")).trim();

            String roomNumber = roomComboBox.getSelectedItem().toString();

            DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
            String date = dateFormat.format(jXDatePicker2.getDate());

            String status ="Booked";

            String time = timeComboBox.getSelectedItem().toString();

            String startTime = time.substring(0, time.indexOf("-")).trim() + ":00";
            String endTime = time.substring(time.indexOf("-")+1).trim() + ":00";

            System.out.println(startTime);
            System.out.println(endTime);

            stmt = connection.prepareCall("{call insertAppointmentRow(?,?,?,?,?,?,?)}");

            stmt.setString(1, patientID);
            stmt.setString(2, status);
            stmt.setString(3, roomNumber);
            stmt.setString(4, date);
            stmt.setString(5, startTime);
            stmt.setString(6, endTime);
            stmt.setString(7, doctorID);

            stmt.executeUpdate();

            JOptionPane.showMessageDialog(null, "Appointment Booked successfully");

            String getEmailID = "select email_address from patient where patient_id = '" + patientID +"'";

            ResultSet email_result = statement.executeQuery(getEmailID);
            String patient_email ="";

            while (email_result.next()) {

                patient_email =      email_result.getString(1).trim();
            }

            CallableStatement stmtEmail = connection.prepareCall("{call send_mail_db(?,?,?,?)}");
            stmtEmail.setString(1, "Wecare_Hospital");
            stmtEmail.setString(2, patient_email);
            stmtEmail.setString(3, TextArea.getText());
            stmtEmail.setString(4, "Appointment Booking with Wecare Hospital");

            stmtEmail.executeUpdate();

            JOptionPane.showMessageDialog(null, "Email Sent successfully");
             verifyButton.setEnabled(true);
        } catch (SQLException e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_bookAppointmentActionPerformed

    private void locationComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_locationComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_locationComboBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea TextArea;
    private javax.swing.JButton bookAppointment;
    private javax.swing.JLabel btn_exit;
    private javax.swing.JTextField contactTextField;
    private javax.swing.JComboBox<String> doctorComboBox;
    private javax.swing.JTextField firstNameTextField;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private org.jdesktop.swingx.JXDatePicker jXDatePicker2;
    private javax.swing.JTextField lastNameTextField;
    private javax.swing.JComboBox<String> locationComboBox;
    private javax.swing.JSeparator nameSeparator;
    private javax.swing.JSeparator nameSeparator1;
    private javax.swing.JSeparator nameSeparator2;
    private javax.swing.JComboBox<String> patientComboBox;
    private javax.swing.JComboBox<String> roomComboBox;
    private javax.swing.JButton searchButton;
    private javax.swing.JComboBox<String> timeComboBox;
    private javax.swing.JButton verifyButton;
    // End of variables declaration//GEN-END:variables

   
   
}
