/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.Admin;

import java.awt.CardLayout;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author apoorva
 */
public class PrescriptionPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageEnterpriseJPanel
     */
    private Statement statement;
    private JPanel userProcessContainer;
    private long pId;
    private String appointmentId ;
     private Connection connection;

    public PrescriptionPanel(Statement statement, JPanel userProcessContainer, Connection connection, String appointmentId) throws SQLException {
        initComponents();
         this.statement = statement;
         this.connection = connection;
         this.appointmentId = appointmentId;
         this.userProcessContainer = userProcessContainer;
         //populateToothTable();

    }
    
//    private void populateToothTable() throws SQLException{
//        DefaultTableModel model = (DefaultTableModel) toothTableResult.getModel();
//         model.setRowCount(0);
//        String patientId = "select patient_id from appointment where appointment_id = " + appointmentId + "";
//        String patId = "";
//        ResultSet rs = statement.executeQuery(patientId);
//         while (rs.next()) {
//        patId = rs.getString(1);
//         }
//        String toothTable = "select tooth_type,tooth_id,treatment_description from tooth where patient_id = " + patId + "";
//        
//        ResultSet rs2 = statement.executeQuery(toothTable);
//         
//        while (rs2.next()) {
//                model.addRow(new Object[]{
//                    rs2.getString(1), 
//                    rs2.getString(2),
//                    rs2.getString(3)
//                });
//            }
//        
//    }

   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        proceedButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        presciptionTable = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        medicineNameTextField = new javax.swing.JTextField();
        nameSeparator4 = new javax.swing.JSeparator();
        morningRadioButton = new javax.swing.JRadioButton();
        afternoonRadioButton = new javax.swing.JRadioButton();
        NightRadioButton = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        notesTextField = new javax.swing.JTextField();
        addPresciptionButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        durationTextField = new javax.swing.JTextField();

        setBackground(new java.awt.Color(55, 96, 128));
        setPreferredSize(new java.awt.Dimension(1100, 617));

        jPanel2.setBackground(new java.awt.Color(55, 96, 128));

        jPanel4.setBackground(new java.awt.Color(23, 35, 51));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Prescription");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1050, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1100, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 72, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 20, Short.MAX_VALUE)))
        );

        proceedButton.setBackground(new java.awt.Color(171, 204, 67));
        proceedButton.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        proceedButton.setText("Generate Invoice");
        proceedButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proceedButtonActionPerformed(evt);
            }
        });

        presciptionTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Medicine name", "Morning", "Afternoon", "Night", "Duration"
            }
        ));
        jScrollPane2.setViewportView(presciptionTable);
        if (presciptionTable.getColumnModel().getColumnCount() > 0) {
            presciptionTable.getColumnModel().getColumn(3).setHeaderValue("Night");
            presciptionTable.getColumnModel().getColumn(4).setHeaderValue("Duration");
        }

        jPanel3.setBackground(new java.awt.Color(55, 96, 128));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        jLabel7.setText("Medicine Name");

        medicineNameTextField.setBackground(new java.awt.Color(55, 96, 128));
        medicineNameTextField.setBorder(null);
        medicineNameTextField.setCaretColor(new java.awt.Color(30, 59, 92));
        medicineNameTextField.setDisabledTextColor(new java.awt.Color(55, 96, 128));
        medicineNameTextField.setOpaque(false);
        medicineNameTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                medicineNameTextFieldFocusGained(evt);
            }
        });
        medicineNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medicineNameTextFieldActionPerformed(evt);
            }
        });

        nameSeparator4.setForeground(new java.awt.Color(0, 0, 0));

        morningRadioButton.setBackground(new java.awt.Color(55, 96, 128));
        morningRadioButton.setText("Morning");
        morningRadioButton.setBorder(null);

        afternoonRadioButton.setBackground(new java.awt.Color(55, 96, 128));
        afternoonRadioButton.setText("Afternoon");
        afternoonRadioButton.setBorder(null);

        NightRadioButton.setBackground(new java.awt.Color(55, 96, 128));
        NightRadioButton.setText("Night");
        NightRadioButton.setBorder(null);

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        jLabel8.setText("Notes");

        addPresciptionButton.setBackground(new java.awt.Color(171, 204, 67));
        addPresciptionButton.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        addPresciptionButton.setText("Add");
        addPresciptionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPresciptionButtonActionPerformed(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(55, 96, 128));
        jLabel4.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Prescription");

        jLabel2.setText("Duration");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(addPresciptionButton)
                .addGap(152, 152, 152))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(notesTextField)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(morningRadioButton)
                                .addGap(18, 18, 18)
                                .addComponent(afternoonRadioButton)
                                .addGap(18, 18, 18)
                                .addComponent(NightRadioButton))
                            .addComponent(nameSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(48, 48, 48)
                                .addComponent(jLabel2))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(medicineNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(67, 67, 67)
                                .addComponent(durationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 27, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(medicineNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(durationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nameSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(morningRadioButton)
                    .addComponent(afternoonRadioButton)
                    .addComponent(NightRadioButton))
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(notesTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(addPresciptionButton)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(proceedButton)
                .addGap(446, 446, 446))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70)
                .addComponent(proceedButton)
                .addContainerGap(174, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void proceedButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proceedButtonActionPerformed
        // TODO add your handling code here:
        
        CallableStatement stmt = null;
        
        try {
            stmt = connection.prepareCall("{call insertInvoiceRow(?)}");
        } catch (SQLException ex) {
            Logger.getLogger(PrescriptionPanel.class.getName()).log(Level.SEVERE, null, ex);
        }

        try {
            stmt.setString(1, appointmentId);
            stmt.executeQuery();
        } catch (SQLException ex) {
            Logger.getLogger(PrescriptionPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
        
        
        
        
        
         InvoicePanel invoicePanel = null;
        try {
            invoicePanel = new InvoicePanel(statement, userProcessContainer, connection, appointmentId);
        } catch (SQLException ex) {
            Logger.getLogger(PrescriptionPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        userProcessContainer.add("InvoicePanel", invoicePanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_proceedButtonActionPerformed

    private void medicineNameTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_medicineNameTextFieldFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_medicineNameTextFieldFocusGained

    private void medicineNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medicineNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_medicineNameTextFieldActionPerformed

    private void addPresciptionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPresciptionButtonActionPerformed
        // TODO add your handling code here:
        
        String medicineName = medicineNameTextField.getText();
        String notes = notesTextField.getText();
        char morning = '0';
        char night = '0';
        char afternon = '0';
        String duration = durationTextField.getText();
        
        if (morningRadioButton.isSelected()){
         morning = '1';
        }
        
        if (NightRadioButton.isSelected()){
         night = '1';
        }
        
        if (afternoonRadioButton.isSelected()){
         afternon = '1';
        }
     
        DefaultTableModel model = (DefaultTableModel) presciptionTable.getModel();
        try {
            statement.executeUpdate("INSERT INTO prescription VALUES ('" 
                    + medicineName +"','" + morning + "','"+ afternon + "','"+ night + "','"
                    + duration + "','"+ notes +  "','"+ appointmentId + "')");
        } catch (SQLException ex) {
            Logger.getLogger(PrescriptionPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        model.addRow(new Object[]
       { medicineName , 
         morning,
         afternon,
         night,
         duration,
         notes

        }); 
        
        
    }//GEN-LAST:event_addPresciptionButtonActionPerformed

    private void populateDefault() throws SQLException {

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton NightRadioButton;
    private javax.swing.JButton addPresciptionButton;
    private javax.swing.JRadioButton afternoonRadioButton;
    private javax.swing.JTextField durationTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField medicineNameTextField;
    private javax.swing.JRadioButton morningRadioButton;
    private javax.swing.JSeparator nameSeparator4;
    private javax.swing.JTextField notesTextField;
    private javax.swing.JTable presciptionTable;
    private javax.swing.JButton proceedButton;
    // End of variables declaration//GEN-END:variables

}
