/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.Admin;

import java.awt.CardLayout;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author apoorva
 */
public class TreatmentPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageEnterpriseJPanel
     */
    private Statement statement;
    private JPanel userProcessContainer;
    private long pId;
    private String appointmentId ;
     private Connection connection;

    public TreatmentPanel(Statement statement, JPanel userProcessContainer, Connection connection, String appointmentId) throws SQLException {
        initComponents();
         this.statement = statement;
         this.connection = connection;
         this.appointmentId = appointmentId;
         this.userProcessContainer =userProcessContainer;
         DefaultTableModel model = (DefaultTableModel) treatmentCatalogueTable.getModel();
         
         
        String getTreatments = "select treatment_name ,treatment_cost from treatment_catalog";
        ResultSet rs = statement.executeQuery(getTreatments);
        while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getString(1), 
                    rs.getString(2)
                });
            }
    }

   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        treatmentCatalogueTable = new javax.swing.JTable();
        proceedButton = new javax.swing.JButton();
        addButton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        treatmentTable = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(55, 96, 128));
        setPreferredSize(new java.awt.Dimension(1100, 617));

        treatmentCatalogueTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Treatment Name", "Treatment Cost"
            }
        ));
        treatmentCatalogueTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(treatmentCatalogueTable);

        proceedButton.setBackground(new java.awt.Color(171, 204, 67));
        proceedButton.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        proceedButton.setText("Proceed");
        proceedButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proceedButtonActionPerformed(evt);
            }
        });

        addButton.setBackground(new java.awt.Color(171, 204, 67));
        addButton.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        addButton.setText("Add");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        treatmentTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Treatment Name", "Treatment Cost"
            }
        ));
        jScrollPane3.setViewportView(treatmentTable);

        jPanel4.setBackground(new java.awt.Color(23, 35, 51));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Treatment Information");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(90, 90, 90)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(addButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(proceedButton, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE))
                .addGap(129, 560, Short.MAX_VALUE))
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(addButton)
                        .addGap(61, 61, 61)
                        .addComponent(proceedButton)))
                .addGap(72, 72, 72)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void proceedButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proceedButtonActionPerformed
        // TODO add your handling code here:
        
       PrescriptionPanel presciption = null;
        try {
            presciption = new PrescriptionPanel(statement, userProcessContainer,connection,appointmentId);
        } catch (SQLException ex) {
            Logger.getLogger(TreatmentPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        userProcessContainer.add("PrescriptionPanel", presciption);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer); 
        
    }//GEN-LAST:event_proceedButtonActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:
        
        int selectedRow = treatmentCatalogueTable.getSelectedRow();
        
       if (selectedRow < 0){
            JOptionPane.showMessageDialog(null, "Please select Treatmen to add" ,"Warning" , JOptionPane.WARNING_MESSAGE);
            return;
        } 
       
       String treatmentName =  treatmentCatalogueTable.getValueAt(selectedRow, 0).toString();
       String treatmentCost    =  treatmentCatalogueTable.getValueAt(selectedRow, 1).toString();
       
       DefaultTableModel model = (DefaultTableModel) treatmentTable.getModel();
        try {
            statement.executeUpdate("INSERT INTO treatment VALUES ('" 
                    + treatmentCost +"','" + appointmentId + "','"+ treatmentName + "')");
             model.addRow(new Object[]
       { treatmentName , 
         treatmentCost  });
       
       JOptionPane.showMessageDialog(null, "Treatment Details Added");
        } catch (SQLException ex) {
            Logger.getLogger(TreatmentPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    
      
     
    }//GEN-LAST:event_addButtonActionPerformed

    private void populateDefault() throws SQLException {

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton proceedButton;
    private javax.swing.JTable treatmentCatalogueTable;
    private javax.swing.JTable treatmentTable;
    // End of variables declaration//GEN-END:variables

}
